### ISSUE TITLE
Windows/Linux shows no colored images

### ISSUE THREAD

**Issue by itsnotyoutoday** [shiraji/yet-another-emoji-support#54]
I installed in phpstorm.... unless I'm missing a setting it doesn't seem to work.  I tried typing in my twig templates, and php comments.. : and some text.. nothing.

**Comment by shiraji** [comment]
Which PhpStorm version are you using?

**Comment by DerAlSem** [comment]
Same here. Weird though - i have it installed in three places (work PC, home PC, travel notebook) - only on travel notebook it doesn't work:

PhpStorm 2019.3 EAP
Build #PS-193.4697.24, built on October 17, 2019
PhpStorm EAP User
Expiration date: November 16, 2019
Runtime version: 11.0.4+10-b520.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 974M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.shiraji.yaemoji, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin

**Comment by DerAlSem** [comment]
Well it's expired, updated to latest version. Still no luck.

PhpStorm 2019.3
Build #PS-193.5233.64, built on November 21, 2019
Licensed to ...
Subscription is active until October 7, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 974M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.shiraji.yaemoji, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin

**Comment by shiraji** [comment]
Thanks for the info. Let me check.

**Comment by shiraji** [comment]
Guys, thanks for reporting. I think v0.0.3 fix this problem. Please reopen if the problem persists.

**Comment by shiraji** [comment]
No.

**Comment by DerAlSem** [comment]
0.0.3 doesn't fix, confirm.

**Comment by shiraji** [comment]
I have no idea. Under this environment, I managed to use this plugin. 

```
PhpStorm 2019.3
Build #PS-193.5233.101, built on November 28, 2019
Licensed to ...
Subscription is active until August 1, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.shiraji.yaemoji, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin
```

These are the screenshots

![スクリーンショット 2019-12-10 1 31 20](https://user-images.githubusercontent.com/3675458/70454109-3ceda500-1aed-11ea-98c8-f8fb7d6a482b.png)
![スクリーンショット 2019-12-10 1 32 20](https://user-images.githubusercontent.com/3675458/70454107-3ceda500-1aed-11ea-9169-f05828f956ff.png)
![スクリーンショット 2019-12-10 1 31 35](https://user-images.githubusercontent.com/3675458/70454108-3ceda500-1aed-11ea-943c-dff18a57d047.png)

I'm not quite sure if it works with Windows. I don't have Windows machine.

Do you have more information like stacktrace, error message, etc?

**Comment by angelside** [comment]
There is few issue from me. (PhpStorm 2019.3.1, Windows 10)

* It's not working inside php docblock _( It's like comment but start with two star, /** )_

```
/**
 * :sm
 */
```

* Emojis, they are not colored images, they are like coming from my font.
* And I think your emojis are outdated or different, because there is no  ```:smile:``` emoji.

-----

![Emoji 2020-01-14 012039](https://i.imgur.com/FMJbeFL.png)

![emoji vscode  2020-01-14 012345](https://i.imgur.com/st9rfG0.png)

**Comment by shiraji** [comment]
Could you insert emoji in your editor without this plugin?

I observed that behavior if OS and/or IDE does not support showing emojis.

**Comment by angelside** [comment]
**It looks like the plugin is doing its job _(except for php docblock, I believe its can be easily fixed)_. Choose and insert emoji.**


And it's start going deeper, **has nothing to do with the plugin**; like using fallback font. I use Segoe UI emoji. Mono emoji issue; it's seems to be related to IntelliJ IDE windows support.

Insert emoji, native way
![win10 emoji keyboard 2020-01-18 221712](https://i.imgur.com/nO7UC5U.png)

Fallback font Segoe UI emoji 
![Fallback font segoe emoji 2020-01-18 222534](https://i.imgur.com/x1N6QZB.png)

plugin -on- with fallback font
![plugin on with fallback font 2020-01-18 223713](https://i.imgur.com/WCsIkNd.png)

**Comment by shiraji** [comment]
I think related issues are here. Please vote up if you want to see emoji in Windows machine.

https://youtrack.jetbrains.com/issue/IDEA-168570
https://youtrack.jetbrains.com/issue/JBR-11

**Comment by BitForger** [comment]
WebStorm 2020.1.1 on MacOS 10.15 has the same issue. Whenever you type colon it throws an error here:

<details>
<summary>Details</summary>

```

kotlin.UninitializedPropertyAccessException: lateinit property emojiList has not been initialized
	at com.github.shiraji.yaemoji.domain.EmojiDataManager.getEmojiList(EmojiDataManager.kt:4)
	at com.github.shiraji.yaemoji.domain.EmojiCompletionProvider.addCompletions(EmojiCompletionProvider.kt:20)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:26)
	at com.github.shiraji.yaemoji.contributor.EmojiCompletionContributor.fillCompletionVariants(EmojiCompletionContributor.kt:35)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:86)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:26)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:59)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.kt:30)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:834)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:819)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$6(CodeCompletionHandlerBase.java:332)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:324)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

**Comment by shiraji** [comment]
@BitForger Thanks for the info. I think that's another issue. Let me check.

**Comment by shiraji** [comment]
@BitForger I couldn't reproduce this issue at WebStorm 2020.1.1 on MacOS 10.15.4. 

The problem may happen if the initialization failed or the memory released. Let me implement re-initialization step if there are no memory.
