### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'font'

### ISSUE THREAD

**Issue by Dragonrun1** [shiraji/yet-another-emoji-support#66]
CLion 2021.1 EAP
Build #CL-211.4961.39, built on January 28, 2021
CLion EAP User
Expiration date: February 27, 2021
Runtime version: 11.0.9.1+11-b1257.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 8
Registry: run.processes.with.pty=TRUE

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'font' of com/intellij/util/ui/JBFont.create must not be null
	at com.intellij.util.ui.JBFont.$$$reportNull$$$0(JBFont.java)
	at com.intellij.util.ui.JBFont.create(JBFont.java)
	at com.intellij.util.ui.JBFont.label(JBFont.java:22)
	at com.intellij.util.IconUtil$1MyIcon.update(IconUtil.java:885)
	at com.intellij.util.IconUtil$1MyIcon.<init>(IconUtil.java:855)
	at com.intellij.util.IconUtil.textToIcon(IconUtil.java:903)
	at com.github.shiraji.yaemoji.domain.EmojiCompletion$Companion.fromCsv(EmojiCompletion.kt:20)
	at com.github.shiraji.yaemoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:16)
	at com.github.shiraji.yaemoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:10)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$1(ApplicationUtil.java:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:46)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by CjS77** [comment]
This also started happening on IntelliJ IDEA Ultimate with the 2021.1 update

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 2969M
Cores: 16
Non-Bundled Plugins: com.intellij.nativeDebug (211.6693.111), com.webschik.doT (1.5.4), name.kropp.intellij.makefile (211.6693.108), org.toml.lang (0.2.145.3797-211), com.vladsch.idea.multimarkdown (3.0.202.112.Legacy), com.jetbrains.lang.ejs (211.6693.65), com.dmarcotte.handlebars (211.6693.44), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72), zielu.gittoolbox (203.5.4), izhangzhihao.rainbow.brackets (6.17), Pythonid (211.6693.115), nl.rubensten.texifyidea (0.7.5), org.jetbrains.plugins.go (211.6693.111), idea.plugin.protoeditor (2.3.1), net.ashald.envfile (3.2.1), org.rust.lang (0.3.145.3797-211), com.github.shiraji.yaemoji (1.0.7)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by shiraji** [comment]
@Dragonrun1 @CjS77 Can you give me a minimum step to reproduce this problem?

**Comment by Dragonrun1** [comment]
Start/re-start CLion. Think it also happens at other random times when it thinks I'm try to enter a emoji but might be a different error then.

**Comment by Dragonrun1** [comment]
Some line numbers look like they changed so thought I'd copy it here again in case it helps. Same as before during exit/start on the same computer.
CLion 2021.1.1
Build #CL-211.7142.21, built on April 22, 2021
Licensed to Michael Cummings
Subscription is active until December 30, 2021.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: Batch Scripts Support (1.0.12), Dilbert (1.9.0.168), String Manipulation (8.15.203.000.3), com.jetbrains.plugins.ini4idea (211.6693.44), com.intellij.plugins.watcher (211.6693.44), com.vecheslav.darculaDarkerTheme (1.2.0), org.editorconfig.editorconfigjetbrains (211.6693.114), org.github.otanikotani.checks-plugin (1.1.9), zielu.gittoolbox (203.5.8), mobi.hsz.idea.gitignore (4.1.0), org.toml.lang (0.2.146.3826-211), com.intellij.plugins.html.instantEditing (211.6693.111), deno (211.6693.108), ru.adelf.idea.dotenv (2021.1), org.rust.lang (0.3.146.3826-211), com.github.shiraji.yaemoji (1.0.7)

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'font' of com/intellij/util/ui/JBFont.create must not be null
	at com.intellij.util.ui.JBFont.$$$reportNull$$$0(JBFont.java)
	at com.intellij.util.ui.JBFont.create(JBFont.java)
	at com.intellij.util.ui.JBFont.label(JBFont.java:22)
	at com.intellij.util.IconUtil$1MyIcon.update(IconUtil.java:887)
	at com.intellij.util.IconUtil$1MyIcon.<init>(IconUtil.java:857)
	at com.intellij.util.IconUtil.textToIcon(IconUtil.java:905)
	at com.github.shiraji.yaemoji.domain.EmojiCompletion$Companion.fromCsv(EmojiCompletion.kt:20)
	at com.github.shiraji.yaemoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:16)
	at com.github.shiraji.yaemoji.action.EmojiPreloadingActivity$preload$callable$1.call(EmojiPreloadingActivity.kt:10)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$1(ApplicationUtil.java:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:41)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by CjS77** [comment]
> @Dragonrun1 @CjS77 Can you give me a minimum step to reproduce this problem?
It just stopped working after the update.

It started working again a few days ago; possibly after the 2021.1.1 update, I can't recall. Sorry, I'm not being very helpful :-/.


IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 2969M
Cores: 16
Non-Bundled Plugins: com.intellij.nativeDebug (211.7142.13), com.webschik.doT (1.5.4), name.kropp.intellij.makefile (211.6693.108), org.toml.lang (0.2.146.3826-211), com.vladsch.idea.multimarkdown (3.0.202.112.Legacy), com.jetbrains.lang.ejs (211.6693.65), com.dmarcotte.handlebars (211.6693.44), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), zielu.gittoolbox (203.5.8), izhangzhihao.rainbow.brackets (6.17), Pythonid (211.7142.45), nl.rubensten.texifyidea (0.7.6), org.jetbrains.plugins.go (211.7142.36), idea.plugin.protoeditor (2.3.1), net.ashald.envfile (3.2.1), org.rust.lang (0.3.146.3826-211), com.github.shiraji.yaemoji (1.0.7)
Kotlin: 211-1.5.0-release-759-IJ6693.72
